### ISSUE TITLE
Allow to playback files from an USB flash 

### ISSUE THREAD

**Issue by gipi** [ciotto/CaprerAVR#1]
Following this [datasheet](http://www.trainelectronics.com/Arduino/MP3Sound/TalkingTemperature/FN-M16P%20Embedded%20MP3%20Audio%20Module%20Datasheet.pdf) seems possible to play file directly from an USB device connected to the pins names`USB+` and `USB-`.

I will try to implement this functionality if I find time at work ;)

**Comment by ciotto** [comment]
I'm waiting for the cable.. XD

**Comment by gipi** [comment]
![1037](https://cloud.githubusercontent.com/assets/1107413/16480484/c3b470ea-3ea6-11e6-8225-9d9265139197.gif)

you are right, I'll try tomorrow to take it.

**Comment by gipi** [comment]
the cable is arrived, where is the functionality?

![didnt-i](https://cloud.githubusercontent.com/assets/1107413/23822804/93844d20-0654-11e7-8bc4-38dff96227ea.jpeg)
