### ISSUE TITLE
Make an IoT sprizzibabbolo

### ISSUE THREAD

**Issue by gipi** [ciotto/CaprerAVR#3]
Could be possible to create a `REST` service with an `ESP8266` module like described [here](http://www.arduinesp.com/wifiwebserver).
![674](https://cloud.githubusercontent.com/assets/1107413/16458686/42401f04-3e20-11e6-8285-4d91bba1f949.gif)

**Comment by ciotto** [comment]
Good idea Senpai..[from China with the van!](http://www.aliexpress.com/item/New-version-ESP-12E-replace-ESP-12-ESP8266-remote-serial-Port-WIFI-wireless-module/32643507082.html?spm=2114.01010208.3.10.1CTSwC&ws_ab_test=searchweb201556_8,searchweb201602_5_10037_10017_405_507_10032,searchweb201603_11&btsid=371e2550-8376-4de0-824e-aa9579664510)

![good](http://l0lz.com/wp-content/uploads/2014/07/That-Moment-When-You-Get-a-Great-Idea-GIF.gif)

**Comment by gipi** [comment]
It's possible to use [this](https://github.com/esp8266/Arduino) and compile/upload from the Arduino IDE

![510](https://cloud.githubusercontent.com/assets/1107413/16482191/fcead7f2-3eae-11e6-948d-1f37c59689a4.gif)

**Comment by ciotto** [comment]
closed with commit 030a9ef5e2a472d446b17d5e15813cdf0348e7aa
